### ISSUE TITLE
is_channel_strip returns dummy channels in second half of ASIC rather than y-channels

### ISSUE THREAD

**Issue by gtrichardson** [nEXO-collaboration/cryo-asic-analysis#4]
For similar reasons as to the incorrect y-strip plotting in issue #2, the analysis class function 'is_channel_strip(chan)' returns the incorrect value for y-channels and their associated dummy channels.

**Comment by ejangelico** [comment]
What's super strange about this is that you can follow the PCB gerbers, the actual traces, into the ASIC inputs, and map the channel numbers to strips vs caps. And the original mapping is correct if one references the gerbers. Meanwhile, the fix is to use a block of dummy capacitor channels. But we have no idea why that is the case, nor do we have confidence that the position mapping is preserved by doing that. So, we have fixed it by cludgeing the mapping, but need to figure out why this is the case.
